### ISSUE TITLE
New folder structure

### ISSUE THREAD

**Issue by dbox** [kni-labs/rrssb#118]
Potential new stucture:
https://gist.github.com/dbox/37325380cc356fad21f4

Notes:
- Currently I'm using `index.html` as the actual demo, but requires the `media` folder, which isn't necessary in the repo. We can remove `media` entirely. 
- Now, since `dist/index.html` doesn't have to be a 1to1 of http://www.kurtnoble.com/labs/rrssb, perhaps we should just have a few different samples there: (5 icons, 10 icons, w/ counter, w/o counter, w/ meta, etc.)

**Questions:**
- Does `rrssb.scss` need to live in `/dist`? I think most people just want the css file.
- `dist/images` should only include minimized icons, correct?
- Does `/dist/css` and `/dist/js` need to include the un-minified versions as well? (I would think no.)
- Should `assets` be called `build` ?

**Bower Questions:**
- Should bower ignore `/assets` ?
- Can we ignore `js/vendor` and just make modernizr and jquery bower dependencies?

//cc @connorwyatt

**Comment by connorwyatt** [comment]
The idea about having a simplified index with multiple examples is a good idea.

In response to your questions:

- No SCSS in `dist`, only production components, same goes for non minified svgs
- No to the non-minified files (again it should be only production components)
- I don't know about `assets` being `build` but `assets` sounds more descriptive to me to be honest
- Yes to ignoring assets if you mean dependencies that rrssb relies on
- And no I would say that you should include modernizr and jquery so that people can download this library and begin working with it straight away

That's my opinion on the project, I can rewrite the gulp file once the project structure has been finalised :)

**Comment by dbox** [comment]
k. We'll sort out the bower ignore stuff in another thread.

I'm good with calling it `/assets`. Do we even need a copy of index in `/assets`? =

**Comment by dbox** [comment]
Also should it even be called index now? Maybe just demo.html

**Comment by connorwyatt** [comment]
Probably not, it's only needed as a template file really and I think that demo.html would be fine to be honest. Cant wait to get v2 out!

**Comment by dbox** [comment]
Agreed. Gist is updated. I'm fine with locking this structure in.

**Comment by dbox** [comment]
Maybe it should be `rrssb-template.html` then. Ha. Naming things = hard.

**Comment by connorwyatt** [comment]
I don’t think that matters too much, either would be fine
