### ISSUE TITLE
Version in Bower.json Needs Formatting

### ISSUE THREAD

**Issue by connorwyatt** [kni-labs/rrssb#95]
The semver needs changing from "**1.76**" to "**1.7.6**" in the bower.json file.

The error is stopping me from doing a bower install to install v > 1.7.

**Comment by dangelov** [comment]
Just tried to install this via bower as well, got the same error.
`bower error         Invalid Version: 1.76`

**Comment by dbox** [comment]
@connorwyatt, @dangelov Should be fixed. Let me know if that works. Sometimes takes a little bit to propogate to bower.

**Comment by dangelov** [comment]
@dbox Thanks for looking into this and fixing it so promptly. I did try a `bower --force update`, but it appears the archive it tries to download (`https://github.com/kni-labs/rrssb/archive/1.7.6.tar.gz`) still contains the `1.76` version string.

**Comment by dbox** [comment]
Ah. I need to update the release. Will do later today.

**Comment by dbox** [comment]
Created a new release. hopefully that fixes it.

**Comment by dangelov** [comment]
I think the tags are still bad. Asking for version 1.7.6 still downloads the old archive that has `1.76` in it.

But then, asking for `1.76` via bower correctly installs version `1.7.6`. If you see from the attached screenshot, release `1.7.6` says it's 1 commit behind master, even if it says "corrected version number".

![screen shot 2015-04-26 at 13 39 32](https://cloud.githubusercontent.com/assets/1392779/7337044/e957d5a2-ec19-11e4-8bbc-9018f705c029.png)

**Comment by dbox** [comment]
haha. BOWER!!!

okay just did a whole new release and went to 1.7.7 just to try to get it to work.Let me know if THAT one works.

As a side note, when the bower file was created it added as `RRSSB` instead of `rrssb`. Which is against protocol. It appears the only choices are:

1. Unregister `RRSSB` then register a new one as `rrssb` (Would this negatively affect people who have it installed as uppercase?)
2. Have both, but only update `rrssb` in future.
3. Leave it as uppercase.

Any thoughts on this @connorwyatt @dangelov ?

**Comment by dangelov** [comment]
There we go... worked nicely now. Thanks for fixing it up.

As for the uppercase naming, I'm just starting out with bower, not much of an experience to back up any of my suggestions. For what it's worth, I did manage to install rrssb easily, wasn't too hard to realize it asked for the uppercase name.

**Comment by connorwyatt** [comment]
Sorted, thanks @dbox  :)

Nice project by the way :)

**Comment by dbox** [comment]
@connorwyatt great. Thanks!

**Comment by dbox** [comment]
re-registered as `rrssb` leaving both for now
